import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import Link from "next/link";
import "./componentes/searchBar.js"
import SearchBar from "./componentes/searchBar.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-4 p-6 bg-slate-900 text-white">
      
          <Link href="/" className="hover:text-blue-400">Inicio</Link>
          <Link href="/catalogo" className="hover:text-blue-400">Ver Películas</Link>

          <SearchBar />
        </nav>
        {children}
      </body>
    </html>
  );
}
